#!/bin/bash

# cats header csv - without repeating headers
# usage: hcat <csv1> <csv2> ...

if [ $# -eq 0 ]; then
    echo "No files specified"
    exit 1
fi

header=$(cat $1|head -n1)
echo $header
for ii in $*; do
    iiHeader=$(cat $ii|head -n1)
    if [[ "$iiHeader" != "$header" ]]; then
	echo "Header mismatch in files: $1 $ii"
	exit 1
    fi
    cat $ii | sed 1d
done
